Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian.vagrant.vm"
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    apt-get install -y php libapache2-mod-php
    systemctl restart apache2

    
    echo '<VirtualHost *:80>
            DocumentRoot /var/www/html
          </VirtualHost>' > /etc/apache2/sites-available/000-default.conf

    echo 'Listen 8081' >> /etc/apache2/ports.conf
    echo '<VirtualHost *:8081>
            DocumentRoot /var/www/php
            <Directory /var/www/php>
                AllowOverride All
                Require all granted
            </Directory>
          </VirtualHost>' > /etc/apache2/sites-available/php.conf

    a2ensite php.conf
    systemctl restart apache2

    mkdir -p /var/www/php
    chown -R www-data:www-data /var/www
  SHELL


  config.vm.provision "file", source: "./01-vagrant/1/index.html", destination: "/home/vagrant/index.html"
  config.vm.provision "file", source: "./01-vagrant/1/index.php", destination: "/home/vagrant/index.php"

  
  config.vm.provision "shell", inline: <<-SHELL
    sudo mv /home/vagrant/index.html /var/www/html/index.html
    sudo mv /home/vagrant/index.php /var/www/php/index.php
  SHELL
end