---
- hosts: static_site
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Copy index.html to web directory
      copy:
        src: ./playbook_static.yml/index.html
        dest: /var/www/html/index.html
