---
- name: Configure Web Servers
  hosts: all
  become: yes

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install PHP and modules for dynamic server
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
      when: inventory_hostname == 'dynamic'

    - name: Disable default Apache site
      ansible.builtin.shell:
        cmd: a2dissite 000-default.conf
      when: inventory_hostname == 'dynamic'

    - name: Download index.html for static server
      get_url:
        url: https://raw.githubusercontent.com/Fenikks/devops-files-23.08/master/02-tools/files/index.html
        dest: /var/www/html/index.html
      when: inventory_hostname == 'static'

    - name: Download index.php for dynamic server
      get_url:
        url: https://raw.githubusercontent.com/Fenikks/devops-files-23.08/master/02-tools/files/index.php
        dest: /var/www/html/index.php
      when: inventory_hostname == 'dynamic'

    - name: Configure Apache to listen on port 8081
      blockinfile:
        path: /etc/apache2/ports.conf
        block: |
          Listen 8081
        create: yes
      when: inventory_hostname == 'dynamic'

    - name: Create virtual host file for 8081 to serve PHP
      blockinfile:
        path: /etc/apache2/sites-available/8081.conf
        block: |
          <VirtualHost *:8081>
            DocumentRoot /var/www/html
            <Directory /var/www/html>
              Options Indexes FollowSymLinks MultiViews
              AllowOverride All
              Require all granted
            </Directory>
          </VirtualHost>
        create: yes
      when: inventory_hostname == 'dynamic'

    - name: Enable 8081 site
      ansible.builtin.shell:
        cmd: a2ensite 8081.conf && systemctl restart apache2
      when: inventory_hostname == 'dynamic'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
