Vagrant.configure("2") do |config|
  
    # Настройка статического сервера
    config.vm.define "static" do |static|
      static.vm.box = "ubuntu/bionic64"
      static.vm.network "private_network", ip: "192.168.56.11"
      static.vm.hostname = "static"
    end
  
    # Настройка динамического сервера
    config.vm.define "dynamic" do |dynamic|
      dynamic.vm.box = "ubuntu/bionic64"
      dynamic.vm.network "private_network", ip: "192.168.56.12"
      dynamic.vm.hostname = "dynamic"
    end
  
    # Общий провижининг Ansible для обеих машин
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.limit = "all"
    end
  end
  