Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
  
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081
  
    config.vm.synced_folder ".", "/vagrant", disabled: false
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  
    config.vm.define "webserver" do |web|
      web.vm.network "private_network", ip: "192.168.56.10"
  
      web.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y sshpass apache2 php libapache2-mod-php
        systemctl start apache2
        systemctl enable apache2
      SHELL
    end
  end
  